blank_issues_enabled: false
contact_links:
  - name: See the upstream repository
    url: https://github.com/yt-dlp/yt-dlp
    about: This is a fork of yt-dlp with minimal modifications. See the original yt-dlp repository first.
